"""HCX 内部原生扩展的静态类型存根。"""

from collections.abc import Sequence


class MotionStatus:
    known: bool
    done: bool
    succeeded: bool
    cancelled: bool
    timed_out: bool


class NativeSdk:
    def __init__(self) -> None: ...
    def connect(self, local_ip: str, remote_ip: str, port: int) -> None: ...
    def close(self) -> None: ...

    @property
    def connected(self) -> bool: ...

    def link_status(self) -> bool: ...
    def alarms(self) -> list[str]: ...
    def clear_alarms(self) -> bool: ...
    def detach_hmi(self) -> bool: ...
    def hmi_detached(self) -> bool: ...
    def soft_emergency_stop_normal(self) -> bool: ...
    def ethercat_master_operational(self, master_index: int) -> bool: ...
    def set_global_enable(self, enabled: bool) -> bool: ...
    def global_enabled(self) -> bool: ...
    def set_single_enable(self, robot_id: int, enabled: bool) -> bool: ...
    def single_enabled(self, robot_id: int) -> bool: ...
    def joints(self, robot_id: int) -> list[float]: ...
    def torque_feedback(self, robot_id: int) -> list[int]: ...
    def joint_out_limit(
        self, robot_id: int, axis_id: int, angle_deg: float, epsilon: float = ...
    ) -> tuple[bool, bool]: ...
    def axis_limits(self, robot_id: int, axis_id: int) -> tuple[float, float]: ...
    def pause(self, robot_id: int, paused: bool) -> bool: ...
    def clear_route(self, robot_id: int, emergency_stop: bool = ...) -> bool: ...
    def set_protection(self, robot_id: int, enabled: bool) -> bool: ...
    def protection_enabled(self, robot_id: int) -> bool: ...
    def move_joints(
        self,
        robot_id: int,
        angles_deg: Sequence[float],
        interrupt: bool,
        acceleration_seconds: float,
        deceleration_seconds: float,
        speed_ratio: float,
        smooth: int,
    ) -> int: ...
    def motion_status(self, sequence: int) -> MotionStatus: ...
    def wait_motion(self, sequence: int, timeout_ms: int) -> MotionStatus: ...
    def pluse_to_servo(self, robot_id: int, angles_deg: Sequence[float]) -> bool: ...
    def pulse_to_servo(self, robot_id: int, angles_deg: Sequence[float]) -> bool: ...
